version: "3.3"
services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "stackoverkata"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"